version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./conf/:/usr/local/etc/redis
      - ./data:/data
    command:
      redis-server