version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9.11-management
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    # volumes:
    #   - ./data:/var/lib/rabbitmq
    