version: "3.8"
services:
  es:
    image: "elasticsearch:7.12.0"
    restart: always
    network_mode: "host"
    container_name: "es"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL","curl -sS http://localhost:9200 ||exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - node.name=es-1
      - network.publish_host=${host1}
    volumes:
      - "/uino/es/data:/usr/share/elasticsearch/data"
      - "./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "/uino/es/logs:/usr/share/elasticsearch/logs"
    deploy:
      resources:
        limits:
          memory: 4G