version: '3.8'
services:
  mysql:
    image: mysql:8.0.27
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    # volumes:
    #    - "/home/docker_home/mysql_home/loc_single/conf:/etc/mysql"
    #    - "/home/docker_home/mysql_home/loc_single/files:/var/lib/mysql-files"
    #    - "/home/docker_home/mysql_home/loc_single/data/:/var/lib/mysql"
    deploy:
      resources:
        limits:
          memory: 1024M