version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    command:
      redis-server --requirepass 123456
    # volumes:
    #   - ./conf/:/usr/local/etc/redis
    #   - ./data:/data