version: '3.8'
services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123456
      MONGO_INITDB_DATABASE: cqjc
      MONGO_USERNAME: uino
      MONGO_PASSWORD: uino@mongo
    volumes:
      - ./mongo:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    deploy:
      resources:
        limits:
          memory: 8G