version: '3.8'
services:
  nginx:
    image: nginx:1.23.3
    restart: always
    container_name: nginx
    ports:
      - 10000:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    deploy:
      resources:
        limits:
          memory: 256M