version: "3.8"
services:
  zookeeper1:
    container_name: "zookeeper1"
    image: "zookeeper:3.8.0"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=${host2}:2888:3888;2181 server.3=${host3}:2888:3888;2181
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 1024M

  zookeeper2:
    container_name: "zookeeper2"
    image: "zookeeper:3.8.0"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    restart: always
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1={host1}:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=${host3}:2888:3888;2181
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 1024M

  zookeeper3:
    container_name: "zookeeper3"
    image: "zookeeper:3.8.0"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    restart: always
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1={host1}:2888:3888;2181 server.2={host2}:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 1024M

  kafka1:
    container_name: "kafka1"
    image: "wurstmeister/kafka:2.13-2.8.1"
    hostname: kafka1
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${host1}:2181,${host2}:2181,${host3}:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ADVERTISED_HOST_NAME: ${host1}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${host1}:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_HEAP_OPTS: -Xms3G -Xmx6G
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      TZ: Asia/Shanghai
      KAFKA_MESSAGE_MAX_BYTES: 209715200
      KAFKA_REPLICA_FETCH_MAX_BYTES: 209715200
      KAFKA_NUM_NETWORK_THREADS: 9
      KAFKA_NUM_IO_THREADS: 16
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 2147483600
      KAFKA_NUM_PARTITIONS: 6

  kafka2:
    container_name: "kafka2"
    image: "wurstmeister/kafka:2.13-2.8.1"
    hostname: kafka2
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: ${host1}:2181,${host2}:2181,${host3}:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ADVERTISED_HOST_NAME: ${host2}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${host2}:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_HEAP_OPTS: -Xms3G -Xmx6G
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      TZ: Asia/Shanghai
      KAFKA_MESSAGE_MAX_BYTES: 209715200
      KAFKA_REPLICA_FETCH_MAX_BYTES: 209715200
      KAFKA_NUM_NETWORK_THREADS: 9
      KAFKA_NUM_IO_THREADS: 16
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 2147483600
      KAFKA_NUM_PARTITIONS: 6

  kafka3:
    container_name: "kafka3"
    image: "wurstmeister/kafka:2.13-2.8.1"
    hostname: kafka3
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: ${host1}:2181,${host2}:2181,${host3}:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ADVERTISED_HOST_NAME: ${host3}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${host3}:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_HEAP_OPTS: -Xms3G -Xmx6G
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      TZ: Asia/Shanghai
      KAFKA_MESSAGE_MAX_BYTES: 209715200
      KAFKA_REPLICA_FETCH_MAX_BYTES: 209715200
      KAFKA_NUM_NETWORK_THREADS: 9
      KAFKA_NUM_IO_THREADS: 16
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 2147483600
      KAFKA_NUM_PARTITIONS: 6
