version: "3.8"
services:
  zookeeper:
    container_name: "zookeeper"
    image: "zookeeper:3.8.0"
    ports:
      - 2181:2181
    restart: always
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 1024M

  kafka:
    container_name: "kafka"
    image: "wurstmeister/kafka:2.13-2.8.1"
    hostname: kafka
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: ${host}:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ADVERTISED_HOST_NAME: ${host}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${host}:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_HEAP_OPTS: -Xms2G -Xmx4G
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      TZ: Asia/Shanghai
      KAFKA_MESSAGE_MAX_BYTES: 18874368
      KAFKA_REPLICA_FETCH_MAX_BYTES: 20971520
      KAFKA_NUM_NETWORK_THREADS: 9
      KAFKA_NUM_IO_THREADS: 16
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 2147483600
      KAFKA_NUM_PARTITIONS: 1
    deploy:
      resources:
        limits:
          memory: 4096M
